### ISSUE TITLE
ark survival ascended server tool

### ISSUE THREAD

**Issue by Smarf67** [Ragonz/Ark-Server-Creation-Tool#1]
the Ark survival ascended server creation tool will not update and there fore the server will not run correctly. have not had this issue before. and now my server will not work.

**Comment by Smarf67** [comment]
when I turn on the server tool and go to update it it will very quickly say that it failed.

**Comment by therimmer96** [comment]
What error are you getting? Can you provide a screenshot please?

**Comment by Smarf67** [comment]
![server problems](https://github.com/Ragonz/Ark-Server-Creation-Tool/assets/164448025/877e3c57-c97a-4c0a-b3b0-36aa82881946)

I think you were helping me also on Discord. I was able to fix it per your recommendation of deleting the depotdownloader folder and then it was able to reinstall and worked just fine. Thank you so much for your help.
