### ISSUE TITLE
can't downlaod  Astraeos

### ISSUE THREAD

**Issue by armijocj** [Ragonz/Ark-Server-Creation-Tool#13]
Hi, when i try to setup astraeos map, i get connection to steam failed. trying again. anyone else having the same issues? 
![Screenshot 2024-10-14 201427](https://github.com/user-attachments/assets/c20a42ec-fcc7-4975-8902-ab4dba7d5af8)

**Comment by Bonamoasb** [comment]
I'm also seeing this issue when trying to update any of my servers (map agnostic issue). Perhaps there was a Steam update changing how DepotDownloader accesses Steam anonymously?

**Comment by therimmer96** [comment]
Delete the depot downloader files and try updating your game. The tool will
automatically download a brand new copy

**Comment by Bonamoasb** [comment]
@therimmer96 Thanks for the recommendation. Though DepotDownloader still fails to connect to Steam several times, it is eventually establishing a connection and applying updates to my servers. Hopefully the recommendation resolves your issue as well @armijocj.

**Comment by JoJetSki** [comment]
@therimmer96 just to say it I ran updates on all 6 of my servers tonight and all updated the first time with no connection retries like "normal".  Have no idea why for the last month or so they have had lots of retries before finally updating.  Not sure if it is just the servers aren't as busy or Steam changed something on their end (fixed a load balancer etc) or it is just a fluke and the problems will continue.  Just giving information as I receive it.

**Comment by therimmer96** [comment]
Make sure you're using the new version. I released and delete depot
downloader so the tool will download it again. Doing this should solve the
update issues
