### ISSUE TITLE
Ark asa Server Server is not running

### ISSUE THREAD

**Issue by speedyon97** [Ragonz/Ark-Server-Creation-Tool#2]
When i cick start server it appears an error code that my ark asa server file ist not downloaded and there are some files missing/broken but i downloadet everything and it is still not working
pls help

**Comment by Smarf67** [comment]
I have had some similar problems and numerous different errors I was able to fix them by deleting the "depotdownloader" file and the tool will reinstall when you update it. This may or may not work but it has worked for me.

**Comment by NSFLscott** [comment]
I had the same issue. I found that mine was that I put some spaces in the install directory when setting up. This tool does not like that and found that it installed the game in a folder it created with only the first word of the directory I gave it. 

Where I asked it to install, Z:\Ark SE Servers\Ark SE Primary
Where I found the install, Z:\Ark\Ark

Hope that helps.

**Comment by therimmer96** [comment]
The issue with spaces in the name has been fixed in 2.0, which is now available.
