### ISSUE TITLE
Issue with Changing Map to Scorched Earth in Server Creation Tool

### ISSUE THREAD

**Issue by ErwinWRLD** [Ragonz/Ark-Server-Creation-Tool#3]
Subject: Issue with Changing Map to Scorched Earth in Server Creation Tool

Hello,

I'm encountering an issue with changing the map to Scorched Earth using the [Server Creation Tool Version] tool. Despite several attempts, I've been unable to successfully switch from The Island to Scorched Earth.

Here's a summary of the steps I've taken:
- I've added the ScorchedEarth_WP folder from ARK Survival Ascended\ShooterGame\Saved\ScorchedEarth_WPSavedArksLocal\ScorchedEarth_WP to the SavedArks directory within the server creation tool's folder structure.
- I've modified the gameusersetting.ini file by adding the line [ServerSettings] MapName=ScorchedEarth_WP to specify the Scorched Earth map.
- I've also tried adding the launch argument -MapName=ScorchedEarth_WP with "Override launch arguments" enabled in the tool's settings.

However, each time I restart or update the server, the tool recreates The Island folder in the SavedArks directory, preventing the map from successfully changing to Scorched Earth. Additionally, when attempting to join the server with the Scorched Earth map configured, my screen remains black, and I am unable to proceed without forcibly closing the game.

As a potential solution, I suggest adding a "change map" button to the server creation tool, which would automate the process of switching maps and ensure that the correct files are added.

Thank you for your attention to this matter. I appreciate your efforts in resolving this issue and look forward to your response.

Best regards,
Erwin

<img width="423" alt="Screenshot_1" src="https://github.com/Ragonz/Ark-Server-Creation-Tool/assets/166341655/99f54899-7c80-4239-9301-a08584653f3d">

**Comment by therimmer96** [comment]
Changing maps is now a feature in 2.0, please let us know if you have any further issues.
